/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.juanxxiii.juansapp.view;

/**
 *
 * @author Dam
 */
public class JPJuansapp extends javax.swing.JPanel {

    /**
     * Creates new form JPJuansapp
     */
    public JPJuansapp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfLastConnection = new javax.swing.JTextField();
        jbLastConnection = new javax.swing.JButton();
        jtfNickname = new javax.swing.JTextField();
        jbNickname = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMessages = new javax.swing.JTextArea();
        jtfMessage = new javax.swing.JTextField();
        jbMessage = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setNextFocusableComponent(jtaMessages);

        jtfLastConnection.setText("Escribe la Dirección de la BBDD");
        jtfLastConnection.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfLastConnectionFocusGained(evt);
            }
        });

        jbLastConnection.setText("Conectar");
        jbLastConnection.setSelected(true);

        jtfNickname.setText("Escribe tu Nickname");
        jtfNickname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNicknameFocusGained(evt);
            }
        });

        jbNickname.setText("Elegir");

        jtaMessages.setColumns(20);
        jtaMessages.setRows(5);
        jScrollPane1.setViewportView(jtaMessages);

        jtfMessage.setText("Escriba aquí su mensaje...");
        jtfMessage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfMessageFocusGained(evt);
            }
        });

        jbMessage.setText("Enviar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfLastConnection, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(jtfNickname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbNickname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbLastConnection, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfLastConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLastConnection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNickname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMessage))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNicknameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNicknameFocusGained
        jtfNickname.setText("");
    }//GEN-LAST:event_jtfNicknameFocusGained

    private void jtfLastConnectionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfLastConnectionFocusGained
        jtfLastConnection.setText("");
    }//GEN-LAST:event_jtfLastConnectionFocusGained

    private void jtfMessageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfMessageFocusGained
        jtfMessage.setText("");
    }//GEN-LAST:event_jtfMessageFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbLastConnection;
    private javax.swing.JButton jbMessage;
    private javax.swing.JButton jbNickname;
    private javax.swing.JTextArea jtaMessages;
    private javax.swing.JTextField jtfLastConnection;
    private javax.swing.JTextField jtfMessage;
    private javax.swing.JTextField jtfNickname;
    // End of variables declaration//GEN-END:variables

}
